import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./header.js";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Levi's Collab",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        
        <div className="fixed top-2 left-3 z-[9999]">
          <Image
            src="/favicon.png"
            alt="Logo"
            width={100}
            height={60}
            style={{ objectFit: "contain" }}
            priority
          />
        </div>

        <div>{children}</div>
      </body>
    </html>
  );
}
